name:                haskell-experiments
version:             0.1.0.0
github:              "lehmacdj/haskell-experiments"
author:              "Devin Lehmacher"
copyright:           "Copyright: (c) 2018"
license:             BSD3

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/lehmacdj/xi-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- transformers
- megaparsec
- validation
- optparse-applicative
- tasty
- tasty-hunit
- tasty-quickcheck
- tasty-smallcheck
- tasty-golden
- text
- tuple
- filepath
- free
- recursion-schemes
- bifunctors
- ansi-wl-pprint
- comonad
- QuickCheck
- mtl
- streams
- smallcheck

ghc-options:
- -Wall
# - -Werror

library:
  source-dirs: src
