name:                cellular-automata
version:             0.1.0.0
github:              "lehmacdj/experiments"
license:             BSD3
author:              "Devin Lehmacher"
maintainer:          "lehmacdj@gmail.com"
copyright:           "Copyright: (c) 2020 Devin Lehmacher"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Miscellaneous

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lehmacdj/experiments#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- array
- comonad
- containers
- deepseq
- diagrams
- diagrams-lib
- diagrams-svg
- directory
- random
- terminal-progress-bar

library:
  source-dirs: src

executables:
  cellular-automata-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - cellular-automata

tests:
  cellular-automata-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cellular-automata
